# @package _global_

defaults:
  - p2p-train
  - datamodule: tartanair
  - _self_

# overrides
task: p2p-train-tartanair

trainer:
  accumulate_grad_batches: 4
  max_epochs: 20
  val_check_interval: 1.0
  num_sanity_val_steps: 0

datamodule:
  split_ratio: [0.85, 0.05, 0.1]
  # include: abandonedfactory_night_Easy
  train_config:
    scale: 0.8
    size: [480, 640]
    batch_size: 1
    wrapper:
      cfg:
        seq_len: 6
        seq_spacing: 6
        item_spacing: 1
        shuffle_series_within: all
  validate_config:
    scale: 1.0
    size: [384, 512]
    batch_size: 8
    dataset:
      needs_depth: True
    wrapper:
      cfg:
        seq_len: 2 # do not change: we need image pairs to evaluate matching
        seq_spacing: 50
        item_spacing: 1
  test_config:
    scale: 1.0
    size: [384, 512]
    batch_size: 8
    dataset:
      needs_depth: True
    wrapper:
      cfg:
        seq_len: 2 # do not change: we need image pairs to evaluate matching
        seq_spacing: 2
        item_spacing: 1

model:
  cfg:
    evaluator: reproj_mma
